changelog:
  exclude:
    labels:
      - ignore for release
  categories:
    - title: Breaking Changes 🚨
      labels:
        - breaking change
    - title: Features 🎉
      labels:
        - feature
    - title: Bugfixes 🐞
      labels:
        - fix
        - bug
        - hotfix
    - title: Misc
      labels:
        - "*"
